FROM python:3.7

COPY . /app

WORKDIR /app

RUN pip install -r requirements.txt

ENV DB_URI = "mysql+pymysql://admin:password1@reddit.cdmy9ha0drjx.us-east-1.rds.amazonaws.com:3306/gs-hackathon"

EXPOSE 5000

CMD gunicorn -w 8 --timeout 300 --log-level debug --bind 0.0.0.0:5000 app:app